#+TITLE: pogoPlugConfig
#+DATE: <2014-07-12 Sat>
#+AUTHOR: George Jones
#+EMAIL: gmj@pobox.com
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:nil todo:t |:t
#+CREATOR: Emacs 24.3.50.1 (Org mode 8.2.5h)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export

This is a log of the steps that I took to re-install arch linux on a
pogoplug 4 and set it up as a local storage device, export nfs and
mount it.  This is done for myself as a record of what I've done
because 1) I might have to repeat the process and 2) someone else
might find it useful.

Start here: http://archlinuxarm.org/platforms/armv5/pogoplug-series-4

* Install basic pogoplug
    
  - [X] Plug in pogoplug power

  - [X] Plug in pogoplug to Internet connected port

  - [X] Go to pogoplug.com/activate

  - [X] Type in 26 digit/number ID on bottom of unit if needed.

  - [X] Enable SSH on the pogoplug web site https://pogoplug.com/settings# if needed (settings/security)

  - [X] Change the password

  - [X] Test SSH.  Get address assigned by DHCP from devices attached
    to local router/WAP (in my case, http://192.168.1.1, login in as
    appropriate and look at connected devices to find pogoplug)

  - [ ] [optional] Assign a fixed address to the pogoplug.  I did this
    by adding a DNS reservation at a fixed address for the MAC address
    of the Pogoplug. 

* Root the Pogoplug
  
  - [X] http://archlinuxarm.org/platforms/armv5/pogoplug-series-4.  I
    used a USB thumb drive in the top USB slot (you have to remove the cover)

  - [X] Reboot

* Attach storage

  - I attached a 2 TB external USB drive to one of the USB ports which
    is formatted with NTFS.  I chose to keep it rather than formatting.

  - [X] install NTFS-3G to enable NTFS writing
    
    #+BEGIN_EXAMPLE
    [root@alarm ~]# pacman -S ntfs-3g
    #+END_EXAMPLE
    
  - [X] Find the partition
     
     #+BEGIN_EXAMPLE
     [root@alarm ~]# fdisk -l
     #+END_EXAMPLE

  - [X] Mount the ntfs partition

     #+BEGIN_EXAMPLE
     [root@alarm ~]# mount -t ntfs-3g /dev/sdb1 /mnt/data
     #+END_EXAMPLE

     I got the following error, because, apparently the partition was
     not correctly dismounted:

     #+BEGIN_EXAMPLE
     [root@alarm ~]# mount -t ntfs-3g /dev/sdb1 /mnt/data
     mount -t ntfs-3g /dev/sdb1 /mnt/data
     $MFTMirr does not match $MFT (record 0).
     Failed to mount '/dev/sdb1': Input/output error
     NTFS is either inconsistent, or there is a hardware fault, or it's a
     SoftRAID/FakeRAID hardware. In the first case run chkdsk /f on Windows
     then reboot into Windows twice. The usage of the /f parameter is very
     important! If the device is a SoftRAID/FakeRAID then first activate
     it and mount a different device under the /dev/mapper/ directory, (e.g.
     /dev/mapper/nvidia_eahaabcc1). Please see the 'dmraid' documentation
     for more details.
     #+END_EXAMPLE

     - [ ] fix NTFS filesystem problem

     Given that I don't have a windows system to run chkdisk with, I'm
     considering reformatting with ext4 or similar and moving on...but
     some quick googling found an answer:
     http://askubuntu.com/questions/47700/fix-corrupt-ntfs-partition-without-windows 
     
     
     #+BEGIN_EXAMPLE
     [root@alarm ~]# ntfsfix /dev/sdb1
     #+END_EXAMPLE
     
     after which 
     
     #+BEGIN_EXAMPLE
     mount -t ntfs-3g /dev/sdb1 /mnt/data
     #+END_EXAMPLE
     
     works just fine.

* Set up permanent mount

  - [X] Find the UUID
    
    #+BEGIN_EXAMPLE
    [root@alarm ~]# blkid /dev/sdb1
    blkid /dev/sdb1
    /dev/sdb1: LABEL="Seagate Expansion Drive" UUID="54F8DF61F8DF3FC2" TYPE="ntfs" PARTUUID="ba02d2a2-01" 
    #+END_EXAMPLE

  - [X] Add a user 
    
    #+BEGIN_EXAMPLE
    useradd -m -g users -G wheel -s /bin/bash user
    #+END_EXAMPLE
    
  - [X] create the fstab entry with linux compatible permissions allowing

    #+BEGIN_EXAMPLE
    cat <<END >> /etc/fstab
    # Mount internal Windows partition with linux compatible permissions, i.e. 755 for directories (dmask=022) and 644 for files (fmask=133)
    UUID=54F8DF61F8DF3FC2 /mnt/data ntfs-3g uid=user,gid=users,dmask=022,fmask=133 0 0
    END
    #+END_EXAMPLE 

* Install NTP

  See
  https://wiki.archlinux.org/index.php/Network_Time_Protocol_daemon#Installation

  #+BEGIN_EXAMPLE
  pacman -S ntp				
  ntpd -q
  systemctl enable ntpd.service
  systemctl start  ntpd.service
  ntpq -p
  #+END_EXAMPLE

* Install NFS
  See https://wiki.archlinux.org/index.php/NFS

  #+BEGIN_EXAMPLE
  pacman -S nfs-utils
  cat <<HERE > /etc/imapd.conf
[General]

Verbosity = 1
Pipefs-Directory = /var/lib/nfs/rpc_pipefs
Domain = atomic

[Mapping]

Nobody-User = nobody
Nobody-Group = nobody
[General]
 
Verbosity = 1
Pipefs-Directory = /var/lib/nfs/rpc_pipefs
Domain = atomic

[Mapping]

Nobody-User = nobody
Nobody-Group = nobody
HERE

  if [ ! -f /etc/conf.d/nfs-common.conf.orig ]; then
    cp /etc/conf.d/nfs-common.conf /etc/conf.d/nfs-common.conf.orig
  fi

  cat /etc/conf.d/nfs-common.conf.orig | sed -e 's/^STATD_OPTS.*/STATD_OPTS="-p 32765 -o 32766 -T 32803"/' > /etc/conf.d/nfs-common.conf


  if [ ! -f /etc/conf.d/nfs-server.orig ]; then
    cp /etc/conf.d/nfs-server.conf /etc/conf.d/nfs-server.conf.orig
  fi

  cat /etc/conf.d/nfs-server.conf.orig | sed -e 's/^MOUNTD_OPTS.*/MOUNTD_OPTS="-p 20048"/' > /etc/conf.d/nfs-server.conf


  systemctl restart nfs-config
  systemctl stop rpc-statd
  systemctl start rpc-statd
  systemctl stop nfs-server
  systemctl start nfs-server
  rpcinfo -p
  #+END_EXAMPLE
    
* Export the filesystem     

  #+BEGIN_EXAMPLE

  if [ ! -f /etc/exports.orig ]; then
    cp /etc/exports /etc/exports.orig
  fi

  cp /etc/exports.orig /etc/exports
  echo "/mnt/data 192.168.1.0/24(rw,no_subtree_check,nohide,all_squash,anonuid=0,anongid=0)" >> /etc/exports

  exportfs -rav
  
  #+END_EXAMPLE

* Start NFS server (now and on reboot)

  #+BEGIN_EXAMPLE
  systemctl enable nfs-server.service
  systemctl start  nfs-server.service
  #+END_EXAMPLE

* Open up firewall rules if needed

  #+BEGIN_EXAMPLE
  if [ ! -f /etc/iptables/iptables.rules.orig ]; then
    cp /etc/iptables/iptables.rules /etc/iptables/iptables.rules.orig
  fi

  cp /etc/iptables/iptables.rules.orig /etc/iptables/iptables.rules

  cat <<HERE >> /etc/iptables/iptables.rules
-A INPUT -p tcp -m tcp --dport 111 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 2049 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 20048 -j ACCEPT
-A INPUT -p udp -m udp --dport 111 -j ACCEPT
-A INPUT -p udp -m udp --dport 2049 -j ACCEPT
-A INPUT -p udp -m udp --dport 20048 -j ACCEPT
If using NFSv3 and the above listed static ports for rpc.statd and lockd these also need to be added to the configuration:

/etc/iptables/iptables.rules
-A INPUT -p tcp -m tcp --dport 32765 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 32803 -j ACCEPT
-A INPUT -p udp -m udp --dport 32765 -j ACCEPT
-A INPUT -p udp -m udp --dport 32803 -j ACCEPT
HERE  
  #+END_EXAMPLE

* Mount from the client by hand (assumes Ubuntu with packages installed)

  #+BEGIN_EXAMPLE
  showmount -e 192.168.1.222
  mount -t nfs 192.168.1.222:/mnt/data /mnt/data
  df
  #+END_EXAMPLE

* Set up mount from fstab

  #+BEGIN_EXAMPLE
if [ ! -f /etc/fstab.orig ]; then
    cp /etc/fstab /etc/fstab.orig
fi

cp /etc/fstab.orig /etc/fstab

cat <<HERE >> /etc/fstab
192.168.1.222:/mnt/data   /mnt/data   nfs4   rsize=8192,wsize=8192,timeo=14,_netdev	0 0
HERE
  #+END_EXAMPLE

* Outstanding Problems





  


 

  
  
