#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil prop:nil
#+OPTIONS: stat:t tags:t tasks:t tex:t timestamp:t toc:nil todo:t |:t
#+TITLE: Security Onion BitTorrent Instructions
#+DATE: <2014-09-04>
#+AUTHOR: George Jones <gmj@pobox.com>
#+EMAIL: gmj@pobox.com
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.3.50.1 (Org mode 8.2.5h)

This documents the process of downloading the latest [[http://blog.securityonion.net/][Security Onion]]
using BitTorrent, as well as the process of creating the .torrent
file.

* How to download Security Onion using BitTorrent

  Assuming you're running the stock Security Onion with the
  transmission client, do the following to download the latest
  version:

  - [ ] Click on the link
    http://port111.com/securityonion-12.04.5-20140903.iso.torrent. This
    will download the .torrent file (to =~/Downloads= by default)
  - [ ] Click on the .torrent file
  - [ ] When transmission comes up with the "Torrent options" window,
    select the .torrent file and click "Open".  The download will
    begin, in ~/Downloads by default
  - [ ] When done, verify the .md5
#+BEGIN_EXAMPLE
$ md5sum securityonion-12.04.5-20140903.iso
MD5 (securityonion-12.04.5-20140903.iso) = bf8dc037ba20a0a559135d3db796fb48
$ cat securityonion-12.04.5-20140903.iso.md5 
bf8dc037ba20a0a559135d3db796fb48  securityonion-12.04.5-20140903.iso
#+END_EXAMPLE

* How to create a .torrent file for Security Onion
** Download and verify the ISO
*** Go to the web page in a browser http://sourceforge.net/projects/security-onion/files/12.04.5/
*** Get a direct download like to use for the webseed
    Start a download with wget. This will do a redirect.

: wget http://downloads.sourceforge.net/project/security-onion/12.04.5/securityonion-12.04.5-20140903.iso

    Grab the redirect URL. This is the real iso download URL.  It will be something like:

: http://hivelocity.dl.sourceforge.net/project/security-onion/12.04.5/securityonion-12.04.5-20140903.iso

    Kill the first wget.  You might consider doing this a couple times
    to get multiple webseeds (downloads.sourceforge.net appears to be
    a round robin DNS rotation pointing at different mirror sites)

I did this and got:

: http://hivelocity.dl.sourceforge.net/project/security-onion/12.04.5/securityonion-12.04.5-20140903.iso
: http://colocrossing.dl.sourceforge.net/project/security-onion/12.04.5/securityonion-12.04.5-20140903.iso
: http://iweb.dl.sourceforge.net/project/security-onion/12.04.5/securityonion-12.04.5-20140903.iso

*** Download the ISO

: wget http://colocrossing.dl.sourceforge.net/project/security-onion/12.04.5/securityonion-12.04.5-20140903.iso

*** Download the .md5 file

: wget wget http://colocrossing.dl.sourceforge.net/project/security-onion/12.04.5/securityonion-12.04.5-20140903.iso.md5

*** Verify the MD5

#+BEGIN_EXAMPLE
$ md5sum securityonion-12.04.5-20140903.iso
MD5 (securityonion-12.04.5-20140903.iso) = bf8dc037ba20a0a559135d3db796fb48
$ cat securityonion-12.04.5-20140903.iso.md5 
bf8dc037ba20a0a559135d3db796fb48  securityonion-12.04.5-20140903.iso
#+END_EXAMPLE

** Create the .torrent file
*** Choose some trackers

  I'm using the list from http://www.publicbt.com/

: udp://tracker.openbittorrent.com:80/announce
: udp://tracker.istole.it:80
: udp://tracker.publicbt.com:80
: udp://tracker.ccc.de:80

  You may find other options here:
  http://en.wikipedia.org/wiki/BitTorrent_tracker#Public_trackers or
  https://www.google.com/search?client=ubuntu&channel=fs&q=open+public+bittorrent+trackers

*** Create the .torrent file using deluge

     I'm using deluge on Ubuntu. Other torrent clients should be
     similar.

     - [ ] Open deluge (=apt-get install deluge= first if needed)
     - [ ] Choose "file -> create torrent" and select the .iso file
     - [ ] Add the "webseed" using the iso download URL. This is important. This is how people can download the file if there are no other seeders.
     - [ ] Save the torrent file.

** Put the .torrent file some place people can get it.
     I put a copy
     here. http://port111.com/securityonion-12.04.5-20140903.iso.torrent
     This could be dropbox, a URL, an email attachment, etc.
     
     Download stats are available here http://port111.com/webalizer/

** Test the download and verify the md5 as above
   - See [[*How to download Security Onion using BitTorrent][How to download Security Onion using BitTorrent]] above.
** Announce the .torrent

     Let people know it's there.  Encourage people to seed (leave their
     clients running a while) after they finish the download.


