#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil prop:nil
#+OPTIONS: stat:t tags:t tasks:t tex:t timestamp:t toc:nil todo:t |:t
#+TITLE: Security Onion BitTorrent Instructions
#+DATE: <2015-08-26 20:13:39 Wednesday>
#+AUTHOR: George Jones <gmj@pobox.com>
#+EMAIL: gmj@pobox.com
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.3.50.1 (Org mode 8.2.5h)

This documents the process of downloading the latest [[http://blog.securityonion.net/][Security Onion]]
using BitTorrent, as well as the process of creating the .torrent
file.

* How to download Security Onion using BitTorrent

  Assuming you're running the stock Security Onion with the
  transmission client, do the following to download the latest
  version:

  - [ ] Click on the link
    http://port111.com/securityonion-12.04.5.3-20150825.iso.torrent. This
    will download the .torrent file (to =~/Downloads= by default)
  - [ ] Click on the .torrent file
  - [ ] When transmission comes up with the "Torrent options" window,
    select the .torrent file and click "Open".  The download will
    begin, in ~/Downloads by default
  - [ ] When done, verify the .md5

    #+begin_src sh  :results output :exports both
    cd ~/Downloads
    md5sum securityonion-12.04.5.3-20150825.iso
    cat securityonion-12.04.5.3-20150825.iso.md5
    #+end_src

    #+RESULTS:
    : 38ee2cf19f884f0916b076163aab58a5  securityonion-12.04.5.3-20150825.iso
    : 38ee2cf19f884f0916b076163aab58a5  securityonion-12.04.5.3-20150825.iso


* How to create a .torrent file for Security Onion
** Download and verify the ISO
*** Go to the web page in a browser http://sourceforge.net/projects/security-onion/files/12.04.5.3/
*** Get a direct download like to use for the webseed
    Start a download with wget. This will do a redirect.

    #+begin_src sh  :results output :exports src
    wget http://downloads.sourceforge.net/project/security-onion/12.04.5.3/securityonion-12.04.5.3-20150825.iso
    #+end_src


    Grab the redirect URL. This is the real iso download URL.  It will be something like:

    #+begin_example
    http://skylineservers.dl.sourceforge.net/project/security-onion/12.04.5.3/securityonion-12.04.5.3-20150825.iso
    #+end_example

    Kill the first wget.  You might consider doing this a couple times
    to get multiple webseeds (downloads.sourceforge.net appears to be
    a round robin DNS rotation pointing at different mirror sites)

    I did this and got:


    #+begin_example
    http://skylineservers.dl.sourceforge.net/project/security-onion/12.04.5.3/securityonion-12.04.5.3-20150825.iso
    http://superb-dca2.dl.sourceforge.net/project/security-onion/12.04.5.3/securityonion-12.04.5.3-20150825.iso
    http://iweb.dl.sourceforge.net/project/security-onion/12.04.5.3/securityonion-12.04.5.3-20150205.iso  
    #+end_example

*** Download the ISO

    #+begin_src sh  :results output :exports code
    cd ~/Downloads
    wget http://iweb.dl.sourceforge.net/project/security-onion/12.04.5.3/securityonion-12.04.5.3-20150825.iso
    #+end_src

*** Download the .md5 file

    #+begin_src sh  :results output :exports both
    date
    cd ~/Downloads
    pwd
    wget http://iweb.dl.sourceforge.net/project/security-onion/12.04.5.3/securityonion-12.04.5.3-20150825.iso.md5 || true
    #+end_src

#+end_example

*** Verify the MD5

    #+begin_src sh  :results output :exports both
    cd ~/Downloads
    md5sum securityonion-12.04.5.3-20150825.iso
    cat securityonion-12.04.5.3-20150825.iso.md5
    #+end_src

    #+RESULTS:
    : e35846293dcecf76e5b8d39f6d48c9de  securityonion-12.04.5.3-20150825.iso
    : e35846293dcecf76e5b8d39f6d48c9de  securityonion-12.04.5.3-20150825.iso


** create the .torrent file
*** Choose some trackers

  I'm using the list (mostly) from https://openbittorrent.com/.
  Trackers tend to change.  You may find other options here:
  http://en.wikipedia.org/wiki/BitTorrent_tracker#Public_trackers or
  https://www.google.com/search?client=ubuntu&channel=fs&q=open+public+bittorrent+trackers

  #+begin_example
udp://tracker.openbittorrent.com:80/announce
udp://tracker.coppersurfer.tk:6969
udp://tracker.leechers-paradise.org:6969
udp://tracker.publicbt.com:80/announce
udp://IPv6.leechers-paradise.org:6969
  #+end_example


*** Create the .torrent file using deluge

     I'm using deluge on Ubuntu. Other torrent clients should be
     similar.

     - [ ] Open deluge (=apt-get install deluge= first if needed)
     - [ ] Choose "file -> create torrent" and select the .iso file
     - [ ] Add the "webseed" using the iso download URL. This is important. This is how people can download the file if there are no other seeders.
     - [ ] Save the torrent file.

** Put the .torrent file some place people can get it.
     I put a copy
     here. http://port111.com/securityonion-12.04.5.3-20150205.iso.torrent
     This could be dropbox, a URL, an email attachment, etc.
     
     Download stats are available here http://port111.com/webalizer/

** Test the download and verify the md5 as above
   - See [[*How to download Security Onion using BitTorrent][How to download Security Onion using BitTorrent]] above.
** Announce the .torrent

     Let people know it's there.  Encourage people to seed (leave their
     clients running a while) after they finish the download.


